"""initial schema

Revision ID: 91577f08a2a8
Revises: 
Create Date: 2026-06-13 11:15:01.979394
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '91577f08a2a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    op.create_table('metric_catalog_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('canonical_unit', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_catalog_items_slug'), 'metric_catalog_items', ['slug'], unique=True)
    op.create_table('monitoring_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope_type', sa.String(length=50), nullable=False),
    sa.Column('scope_value', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('normalization_knowledge_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_normalization_knowledge_versions_version'), 'normalization_knowledge_versions', ['version'], unique=True)
    op.create_table('company_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('alias_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'alias', name='uq_company_alias')
    )
    op.create_index(op.f('ix_company_aliases_alias'), 'company_aliases', ['alias'], unique=False)
    op.create_table('metric_catalog_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_catalog_item_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['metric_catalog_item_id'], ['metric_catalog_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_catalog_item_id', 'alias', name='uq_metric_catalog_alias')
    )
    op.create_index(op.f('ix_metric_catalog_aliases_alias'), 'metric_catalog_aliases', ['alias'], unique=False)
    op.create_table('publication_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('result_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('effective_url', sa.String(length=2048), nullable=False),
    sa.Column('content_hash', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_state', sa.String(length=50), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_result_documents_content_hash'), 'result_documents', ['content_hash'], unique=True)
    op.create_table('canonical_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('result_document_id', sa.Integer(), nullable=False),
    sa.Column('metric_catalog_item_id', sa.Integer(), nullable=False),
    sa.Column('reference_year', sa.Integer(), nullable=False),
    sa.Column('reference_quarter', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('value_status', sa.String(length=50), nullable=False),
    sa.Column('canonical_unit', sa.String(length=50), nullable=False),
    sa.Column('reported_value', sa.Float(), nullable=True),
    sa.Column('reported_unit', sa.String(length=100), nullable=True),
    sa.Column('coverage_status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['metric_catalog_item_id'], ['metric_catalog_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['result_document_id'], ['result_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extraction_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_document_id', sa.Integer(), nullable=False),
    sa.Column('contract_version', sa.String(length=50), nullable=False),
    sa.Column('llm_provider', sa.String(length=100), nullable=False),
    sa.Column('llm_model', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_contract_payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['result_document_id'], ['result_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publication_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('publication_source_id', sa.Integer(), nullable=False),
    sa.Column('signal_url', sa.String(length=2048), nullable=False),
    sa.Column('signal_title', sa.String(length=500), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['monitoring_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publication_source_id'], ['publication_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reprocessing_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_document_id', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.String(length=100), nullable=False),
    sa.Column('trigger_version', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['result_document_id'], ['result_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('result_document_id', 'trigger_type', 'trigger_version', name='uq_reprocessing_request_trigger')
    )
    op.create_table('candidate_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('extraction_run_id', sa.Integer(), nullable=False),
    sa.Column('reported_metric_name', sa.String(length=255), nullable=False),
    sa.Column('candidate_metric_category', sa.String(length=100), nullable=False),
    sa.Column('value_status', sa.String(length=50), nullable=False),
    sa.Column('reported_value', sa.Float(), nullable=True),
    sa.Column('reported_unit', sa.String(length=100), nullable=True),
    sa.Column('canonical_numeric_value', sa.Float(), nullable=True),
    sa.Column('canonical_unit_hint', sa.String(length=100), nullable=True),
    sa.Column('warnings_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('canonical_metric_cuts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_metric_id', sa.Integer(), nullable=False),
    sa.Column('dimension', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['canonical_metric_id'], ['canonical_metrics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_discovery_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_document_id', sa.Integer(), nullable=False),
    sa.Column('publication_signal_id', sa.Integer(), nullable=False),
    sa.Column('link_type', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['publication_signal_id'], ['publication_signals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['result_document_id'], ['result_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_fact_cuts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_fact_id', sa.Integer(), nullable=False),
    sa.Column('dimension_label', sa.String(length=100), nullable=False),
    sa.Column('value_label', sa.String(length=255), nullable=False),
    sa.Column('is_material', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_fact_id'], ['candidate_facts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extraction_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_fact_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_label', sa.String(length=255), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_fact_id'], ['candidate_facts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extraction_evidence')
    op.drop_table('candidate_fact_cuts')
    op.drop_table('document_discovery_links')
    op.drop_table('canonical_metric_cuts')
    op.drop_table('candidate_facts')
    op.drop_table('reprocessing_requests')
    op.drop_table('publication_signals')
    op.drop_table('extraction_runs')
    op.drop_table('canonical_metrics')
    op.drop_index(op.f('ix_result_documents_content_hash'), table_name='result_documents')
    op.drop_table('result_documents')
    op.drop_table('publication_sources')
    op.drop_index(op.f('ix_metric_catalog_aliases_alias'), table_name='metric_catalog_aliases')
    op.drop_table('metric_catalog_aliases')
    op.drop_index(op.f('ix_company_aliases_alias'), table_name='company_aliases')
    op.drop_table('company_aliases')
    op.drop_index(op.f('ix_normalization_knowledge_versions_version'), table_name='normalization_knowledge_versions')
    op.drop_table('normalization_knowledge_versions')
    op.drop_table('monitoring_jobs')
    op.drop_index(op.f('ix_metric_catalog_items_slug'), table_name='metric_catalog_items')
    op.drop_table('metric_catalog_items')
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
