sonar.sources=felipe-campelo/projeto-4/src
sonar.tests=felipe-campelo/projeto-4/tests
sonar.python.version=3.12

sonar.exclusions=**/.venv/**,**/__pycache__/**,**/.pytest_cache/**,**/.mypy_cache/**,**/htmlcov/**
sonar.coverage.exclusions=felipe-campelo/projeto-4/tests/**,felipe-campelo/projeto-4/alembic/**,felipe-campelo/projeto-4/docs/**,felipe-campelo/projeto-4/.env.example
sonar.cpd.exclusions=felipe-campelo/projeto-4/tests/**,felipe-campelo/projeto-4/alembic/**,felipe-campelo/projeto-4/docs/**,felipe-campelo/projeto-4/README.md,felipe-campelo/projeto-4/.env.example
